version: "3.9"

services:
  # Default User
  # username: elastic
  # password: admin
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2-arm64
    container_name: elasticsearch
    restart: unless-stopped
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata:/usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
      - ELASTIC_PASSWORD=admin
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.enrollment.enabled=true
    networks:
      - esnet
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    image: kibana:8.4.2
    container_name: kibana
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - esnet
    ports:
      - "5601:5601"

  local-rabbitmq:
    image: rabbitmq:3.8.33-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/config/config.conf:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq/log/:/var/log/rabbitmq

volumes:
  certs:
    driver: local
  esdata:
    driver: local

networks:
  esnet:
    name: esnet