name: 'Pull request: Run unit test'

on:
  pull_request:
    branches:
      - dev
      - beta
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Download dependencies
        run: go mod download

      - name: Vet
        run: |
          go vet ./...

      - name: Test
        run: |
          go test  -v -coverpkg ./src/domain/... -coverprofile coverage.out -covermode count ./src/...
          go tool cover -func="./coverage.out"
